name: Build
on:
  push:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          components: clippy, rustfmt
          default: true
      - name: Build binary
        run: |
          cargo build --verbose --release
      - name: Check workflow permissions
        id: check_permissions
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy action to produce annotations
        uses: actions-rs/clippy-check@v1.0.7
        if: steps.check_permissions.outputs.has-permission
        with:
          args: --all-targets -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy manually without annotations
        if: ${{ !steps.check_permissions.outputs.has-permission }}
        run: cargo clippy --all-targets -- -D warnings
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: stevenarella.exe
          path: target/release/stevenarella.exe
      - name: Release binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/stevenarella.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
